[platformio]
default_envs = test

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_extra_dirs = lib
build_flags =
    -Ilib/irrigation_controller
monitor_speed = 9600

[env:test]
platform = native

build_unflags =
    -Isrc

lib_extra_dirs = lib

build_flags =
    -std=gnu++17
    -Ilib/irrigation_controller
    -Itest/native
    